apiVersion: apps/v1
kind: Deployment
metadata:
  name: studybud
  labels:
    app: studybud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studybud
  template:
    metadata:
      labels:
        app: studybud
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 400m
            memory: 400Mi
        volumeMounts:
        - name: static
          mountPath: /usr/src/app/static
        - name: media
          mountPath: /usr/src/app/media
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      - name: studybud
        image: ghcr.io/0xtejas/studybud:k8-latest
        ports:
        - containerPort: 8080
        command: ["sh", "-c", "./entrypoint.sh && gunicorn studybud.wsgi:application --bind 0.0.0.0:8000 -w 2 --access-logfile - --error-logfile -"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        volumeMounts:
        - name: static
          mountPath: /usr/src/app/static
        - name: media
          mountPath: /usr/src/app/media
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        - containerPort: 33060
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-db
              key: MYSQL_DATABASE
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1500m
            memory: 512Mi
        volumeMounts:
        - name: mysql-pvc
          mountPath: /var/lib/mysql
      imagePullSecrets:
      - name: ghcr-credentials
      volumes:
      - name: static
        persistentVolumeClaim:
          claimName: static-pvc
      - name: media
        persistentVolumeClaim:
          claimName: media-pvc
      - name: mysql-pvc
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: nginx-config
        configMap:
          name: nginx-config
