apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: studybud
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
    - name: mysql-ssl
      protocol: TCP
      port: 33060
      targetPort: 33060
  type: ClusterIP